sudo: required
language: python
python:
  -  3.3
  -  3.4
  -  3.5
# whitelist
branches:
  only:
    - master

# command to install dependencies
install:
  - sudo apt-get install python3-dev python-matplotlib
  - pip install -r requirements.txt
# command to run tests
script: nosetests --exe --verbosity=2
env:
  PYTHONPATH=./
