###############################################################################
#
# infoset example: SNMP hostnames
#
###############################################################################
#
# infoset will attempt to communicate with all devices listed in this file. This
# separation was made possible so scripts could be written to automatically
# populate new hosts in this file without the need to affect other configurtion
# files in the directory.
#
# hosts: There must only be one of these keys in all files in the config
#   directory
#
# Read the README.md file for explanations of all the parameters here
#

hosts:
    - host1
    - host2
    - host3
