server: 192.168.1.218
port: 5000
https: False
cache_dir: /tmp
log_file: /tmp/infosetd.log
descriptions:
    Sentry3_infeedPower: Input Power Per Phase
    Sentry3_infeedLoadValue: Input Current Per Phase
    Sentry3_infeedName: Input Power Phase Name
    Sentry3_Sentry3_infeedID: Input Power Phase ID
