common:
    log_file: /home/infoset/infoset.logs/infoset.log
    language: en
    server: True

server:
    agent_root_directory:
    web_directory: /home/infoset/public_html
    data_directory: /home/infoset/infoset/data
    ingest_cache_directory: /home/infoset/infoset.cache/ingest
    ingest_threads: 20
    agent_threads: 10
    db_hostname: localhost
    db_username: infoset
    db_password: wt8LVA7J5CNWPf75
    db_name: infoset
    hosts:
        - 192.168.1.254
        - 192.168.1.1
        - 192.168.1.2
        - 192.168.1.3
        - 192.168.1.4

agents_common:
    server_name: 192.168.3.100
    server_port: 5000
    server_https: False
    agent_cache_directory: /home/infoset/infoset.cache/agents

agents:
    - agent_name: _infoset
      agent_enabled: True
      agent_filename: bin/agents/_infoset.py

    - agent_name: ingestd
      agent_enabled: True
      agent_filename: bin/agents/ingestd.py

    - agent_name: linux
      agent_enabled: True
      agent_filename: bin/agents/linux.py
      agent_port: 5001
      agent_hostnames:
        - 192.168.3.100

    - agent_name: linux_passive
      agent_enabled: True
      agent_filename: bin/agents/linux_in.py

    - agent_name: snmp
      agent_enabled: True
      agent_filename: bin/agents/snmp.py
      agent_hostnames:
        - 192.168.3.100

snmp_groups:
    - group_name: HOME
      snmp_version: 2
      snmp_secname:
      snmp_community: zYDsg7t4BqbegY6
      snmp_port: 161
      snmp_authprotocol:
      snmp_authpassword:
      snmp_privprotocol:
      snmp_privpassword:

    - group_name: PRIV_01
      snmp_version: 3
      snmp_secname: user_priv_01
      snmp_community:
      snmp_port: 161
      snmp_authprotocol: md5
      snmp_authpassword: dW97hNrL8mFkjxRT
      snmp_privprotocol: des
      snmp_privpassword: 5wjUShs8jEy9v3WE

    - group_name: V2
      snmp_version: 2
      snmp_secname:
      snmp_community: Q6RNgKDntG77xseZ
      snmp_port: 161
      snmp_authprotocol:
      snmp_authpassword:
      snmp_privprotocol:
      snmp_privpassword:

    - group_name: PRIV_00
      snmp_version: 3
      snmp_secname: user_priv_00
      snmp_community:
      snmp_port: 161
      snmp_authprotocol: sha
      snmp_authpassword: Kj7PSgHSwCgPErxq
      snmp_privprotocol: aes
      snmp_privpassword: CdgkMAvYTd7qPWVy

    - group_name: AUTH_00
      snmp_version: 3
      snmp_secname: user_auth_00
      snmp_community:
      snmp_port: 161
      snmp_authprotocol: sha
      snmp_authpassword: 7g8aYMhS29MHJzvS
      snmp_privprotocol:
      snmp_privpassword:

    - group_name: NOAUTH_00
      snmp_version: 3
      snmp_secname: user_noauth
      snmp_community:
      snmp_port: 161
      snmp_authprotocol:
      snmp_authpassword:
      snmp_privprotocol:
      snmp_privpassword:
